# Generated by Django 3.0.4 on 2020-03-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choiceText',
            new_name='choice_text',
        ),
    ]
